# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "http://www.demonhacks.com"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-102955394-1"


# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "DemonHacks | October 2017 | DemonHacks "
  description: "DemonHacks."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name: "DemonHacks"
  description: >
    Disregard Sleep;
    Pursue Greatness;
  date:        "October 27th - 29th"
  location:    "Chicago, IL, United States"

  trust_badge:
    year:   "2018"  # season year
    region: "na"    # "na" or "eu"
    color:  "blue" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        href: "https://cssdepaul.typeform.com/to/lDQGNU"
        redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "/#sponsors"

  about:
    description: >
      DemonHacks is a 36-hour hackathon hosted by DePaul University in Chicago, IL. DePaul's Loop campus is right next to the Art Institute 
      of Chicago and Millenium Park. 

  # Frequently asked questions.
  faq:
    - question: "Where is Chicago?"
      answer: >
        [Right here](http://bfy.tw/1CQf)
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing, attending a hackathon is free!
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at DePaul University's loop campus in our College of Computing and Digital Media building located at 243 S Wabash Ave, Chicago, IL 60604.
    - question: "Will there be travel reimbursement?"
      answer: >
        [Click Here to find out](https://goo.gl/w9TwfR)
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is, you can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "What should I bring to a Hackathon?"
      answer: >
        <p>
        We recommend that you bring anything you'd need for an extended stay away from home:
        <p> 
        <ul>
        <li>toiletries (deodorant, toobrush, toothpaste, etc...);    
        <li>Laptop and charger; 
        <li>Phone and charger; 
        <li>Sleeping bag;
        <li>Thermarest;
        <li>Appropriate changes of clothes (remember, you're in the Windy City!);
        <ul>

  # Schedule:
  schedule:
    - day: "Friday"
      event: [
      "5:00 pm - 6:00 pm - Check-in", 
      "5:00 pm - 8:00 pm - Meet the Sponsors",  
      "6:00 pm - 7:00 pm - Dinner", 
      "8:15 pm - 9:00 pm - Opening ceremony", 
      "9:30 pm - END     - Hacking starts"]
    - day: "Saturday"
      event: [ 
      "7:00 am - 9:00 am - Breakfast", 
      "1:00 pm - 2:30 pm - Lunch", 
      "3:00 pm - 4:00 pm - Capture the Flag", 
      "6:00 pm - 7:30 pm - Dinner"]
    - day: " Sunday"
      event: [
      "7:00  am - 9:00 am - Breakfast",
      "8:30  am <t>       - Hacking ends",
      "10    am <t>       - Project Expo",
      "12:30 pm - 1:30 pm - Closing Ceremony"]

    
  sponsors:
    message: >
        More Sponsors coming soon! <br/> If you're interested in sponsoring, please email us at sponsor@demonhacks.com.
  # This is the message you'll receive once you've registered.
    already_sponsoring:
      - sponsor: "../images/balsamiq-logo-screen.svg"
        sponsor_link: "https://balsamiq.com/"
        size: "col-xs-12 col-sm-10 col-sm-offset-1 col-md-4 col-md-offset-2 col-lg-4"
      - sponsor: "../images/Discover.png"
        sponsor_link: "https://www.discover.com/"
        size: "col-xs-12 col-sm-10col-md-4 col-lg-4"
      - sponsor: "../images/M_Sltns_blu_rgb_vc_pos.png"
        sponsor_link: "https://www.motorolasolutions.com/"
        size: "col-xs-12 col-sm-10 col-md-4 col-lg-4"
      - sponsor: "../images/C1_Core_NG_RGB_R.png"
        sponsor_link: "https://www.capitalone.com/"
        size: "img col-xs-12 col-md-6col-lg-4 col-lg-offset-2"
      - sponsor: "../images/NHDS_Registered_Logo.svg"
        sponsor_link: "https://www.neighborhoods.com/"
        size: "img col-xs-12 col-md-6 col-lg-4 col-lg-offset-2"
      #- sponsor: "https://i.imgflip.com/1vc5q4.jpg"
      #  sponsor_link: ""
      #  size: "img col-xs-3 col-md-3"
      #- sponsor: "https://i.imgflip.com/1vc5q4.jpg"
      #  sponsor_link: ""
      #  size: "img col-xs-3 col-md-3"
    register:
        message: >
            You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
