# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "http://www.demonhacks.com"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-102955394-1"


# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "DemonHacks | October 2019 | DemonHacks2019 | DemonHacks2019"
  description: "DemonHacks."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name: "DemonHacks"
  description: >
    Applications for DH are now open!
  date:        "October 19th - 20st"
  location:    "Chicago, Illinois"

# trust_badge:
#     year:   "2020"  # season year
#     region: "na"    # "na" or "eu"
#     color:  "blue" # "white", "black", "gray", "red", "blue" or "yellow"
  #trust_badge:
  #   year:   "2019"  # season year
  #   region: "na"    # "na" or "eu"
  #   color:  "blue" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
     - text: "Apply"
       href: "https://cssdepaul.typeform.com/to/vHvHLN"
       id: "apply-btn"
#        redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
     - text: "Sponsor"
       href: "/#sponsors"
       id: "sponsor-btn"

  about:
    description: >
      DemonHacks is a 26-hour hackathon hosted by DePaul University in Chicago, Illinois. DePaul's Loop campus is right next to the Art Institute
      of Chicago and Millenium Park.

  # Frequently asked questions.
  faq:
    - question: "Are applications open?"
      answer: >
        Applications are now open. Please click the "apply" button at the top of the page. If you're a local student, feel free to come by as a walk-in. Chances are we'll be able to let you in! Email team@demonhacks.com with any concerns.
    - question: "I'm a beginner; am I welcome?"
      answer: >
        Of course! Hackathons are a great place to learn new technologies, meet new people, 
        network with sponsors, add something to your resume, and eat some free food ;).
    - question: "Where is Chicago?"
      answer: >
        [Right here](http://bfy.tw/1CQf)
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing, attending a hackathon is free!
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at DePaul University's loop campus in our College of Computing and Digital Media building located at 243 S Wabash Ave, Chicago, IL 60604.
    - question: "Will there be travel reimbursement?"
      answer: >
        Stay tuned. Minor gas or train reimbursement may be provided.
      # [Click Here to find out](https://goo.gl/w9TwfR)
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a Code of Conduct?"
      answer: >
        Yes there is, you can [find it here](https://docs.google.com/document/d/1PMGI1uPcY5EK_QNh1LPqMbNhTSasOldya0_Zo8P1MDU/mobilebasic?usp=gmail#heading=h.d11fprrgzyp).
    - question: "Are walk-ins allowed?"
      answer: >
        If you were unable to register, we will take walk-ins on a first-come, first-serve basis.
      # provide a time once we know
    # - question: "Do I need to bring any hardware?"
    #   answer: >
    #     MLH will be lending out hardware from their hardware lab, so you're all set!
    - question: "What should I bring to a Hackathon?"
      answer: >
        <p>
        We recommend that you bring anything you'd need for an extended stay away from home:
        <p>
        <ul>
        <li>toiletries (deodorant, toobrush, toothpaste, etc...);
        <li>Laptop and charger;
        <li>Phone and charger;
        <li>Sleeping bag;
        <li>Thermarest;
        <li>Appropriate changes of clothes (remember, you're in the Windy City!);
        <ul>
    - question: "Any more questions?"
      answer: >
        Email us at [team@demonhacks.com](mailto:team@demonhacks.com).

  # Schedule:
  schedule:
    - day: "Check back soon!!"
    # - day: "Saturday"
    #   event: [
    #   "9:00 am - 10:00 am - Check-In",
    #   "9:00 am - 2:00 pm - Meet the Sponsors",
    #   "10:00 am - 11:00 am - Breakfast",
    #   "11:00 am - 11:30 am - Opening Ceremony",
    #   "11:30 am - HACKING STARTS!",
    #   "11:30 am - 12:30 pm - Team Forming Event",
    #   "1:30 pm - 2:30 pm - Lunch",
    #   "2:30 pm - 3:30 pm - Tech Talk or Workshop",
    #   "6:30 pm - 7:30 pm - Dinner",
    #   "8:00 pm - 9:00 pm - Cup Stacking!",
    #   "10:00 pm - 11:00 pm - Tech Talk or Workshop",
    #   "Midnight - Midnight Snack"
    #   ]
    # - day: " Sunday"
    #   event: [
    #   "8:00 am - 10:00 am - Breakfast",
    #   "10:00 am - 11:00 am - Tech Talk or Workshop",
    #   "2:00 pm - 3:00 pm - Lunch",
    #   "2:30 pm - HACKING ENDS!",
    #   "3:30 pm - 4:30 pm Project Expo",
    #   "5:00 pm - 5:30 pm - Closing Ceremony"]


  sponsors:
    message: >
        Our previous sponsors. More coming soon. <br/> If you're interested in sponsoring, please email us at sponsor@demonhacks.com.
  # This is the message you'll receive once you've registered.
    already_sponsoring:
      - sponsor: "../images/JPMC-Logo-Black.png"
        sponsor_link: "https://www.jpmorganchase.com/"
        size: "col-xs-12 col-sm-10col-md-4 col-lg-4"
      - sponsor: "../images/Discover.png"
        sponsor_link: "https://www.discover.com/"
        size: "col-xs-12 col-sm-10col-md-4 col-lg-4"
      - sponsor: "../images/FBB_Lockup_FB_IG__Black.jpg"
        sponsor_link: "https://facebook.com/"
        size: "col-xs-12 col-sm-10 col-sm-offset-1 col-md-4 col-md-offset-2 col-lg-4"
      - sponsor: "../images/relativity.png"
        sponsor_link: "https://www.relativity.com/"
        size: "col-xs-12 col-sm-10col-md-4 col-lg-4"
      - sponsor: "../images/balsamiq-logo-screen.svg"
        sponsor_link: "https://balsamiq.com/"
        size: "col-xs-12 col-sm-10 col-sm-offset-1 col-md-4 col-md-offset-2 col-lg-4"
      # - sponsor: "../images/M_Sltns_blu_rgb_vc_pos.png"
      #   sponsor_link: "https://www.motorolasolutions.com/"
      #   size: "col-xs-12 col-sm-10 col-md-4 col-lg-4"
      # - sponsor: "../images/C1_Core_NG_RGB_R.png"
      #   sponsor_link: "https://www.capitalone.com/"
      #   size: "img col-xs-12 col-md-6col-lg-4 col-lg-offset-2"
      # - sponsor: "../images/NHDS_Registered_Logo.svg"
      #   sponsor_link: "https://www.neighborhoods.com/"
      #   size: "img col-xs-12 col-md-6 col-lg-4 col-lg-offset-2"
      - sponsor: "../images/brooksource.png"
        sponsor_link: "https://www.brooksource.com"
        size: "img col-xs-3 col-md-3"
      - sponsor: "../images/mlh-logo-color.svg"
        sponsor_link: "https://mlh.io"
        size: "img col-xs-3 col-md-3"
      - sponsor: "../images/saf-b-logo.png"
        sponsor_link: ""
        size: "img col-xs-3 col-md-3"
      - sponsor: "../images/stickermule.png"
        sponsor_link: "https://www.stickermule.com/"
        size: "col-xs-12 col-sm-10col-md-4 col-lg-4"
    register:
        message: >
            You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
